#
# Please avoid changing the Exynos defconfig files and use this file to
# add any Motorola-specific configuration changes that are applicable to
# userdebug, eng, and user builds.
#
# After building, a list of all of the config files that are used can be found
# at the top of:
# out/target/product/$(PRODUCT)/obj/KERNEL_OBJ/mapphone_defconfig
#
# The actual output of the kernel configuration system can be found at:
# out/target/product/$(PRODUCT)/obj/KERNEL_OBJ/.config
#
# You can check the .config file to verify that your configuration option is
# being set as expected.
#

# WLBT platform
CONFIG_SCSC_WLBT_CONFIG_PLATFORM="leman_s620_robusta2_dualfem"

# Charger (kane has small charger)
CONFIG_SMALL_CHARGER=y
CONFIG_CHARGER_S2MCS02=y

# Camera sensors (CIS)
CONFIG_CAMERA_CIS_2X5SP_OBJ=y
CONFIG_CAMERA_CIS_GM1SP_OBJ=y

# Camera actuator
CONFIG_CAMERA_ACT_DW9839_OBJ=y

# Camera OIS (kane has OIS)
CONFIG_CAMERA_OIS_SELECT=y
CONFIG_CAMERA_OIS_BU24218GWL_OBJ=y
CONFIG_OIS_DIRECT_FW_CONTROL=y

# Camera EEPROM
CONFIG_CAMERA_EEPROM_GM1_OBJ=y
CONFIG_CAMERA_EEPROM_5E9_OBJ=y
