obj-$(CONFIG_CAMERA_FPGA_DPHY) += fimc-is-fpga-dphy.o

EXTRA_CFLAGS += -I $(srctree)/drivers/media/platform/exynos/fimc-is2
EXTRA_CFLAGS += -I $(srctree)/drivers/media/platform/exynos/fimc-is2/include
EXTRA_CFLAGS += -I $(srctree)/drivers/media/platform/exynos/fimc-is2/vendor
EXTRA_CFLAGS += -I $(srctree)/drivers/media/platform/exynos/fimc-is2/sensor
